### ISSUE TITLE
Underterministic output

### ISSUE THREAD

**Issue by renatoathaydes** [Depado/bfchroma#5]
Hi, I am having trouble writing tests when using this library.

The following test always fails:

```go
import (
	"bufio"
	"fmt"
	"github.com/Depado/bfchroma"
	"github.com/renatoathaydes/magnanimous/mg"
	"gopkg.in/russross/blackfriday.v2"
	"strings"
	"testing"
)

func TestBfChroma(t *testing.T) {
	var chromaRenderer = blackfriday.WithRenderer(bfchroma.NewRenderer(bfchroma.WithoutAutodetect()))

	examples := []string{
		"# hello\n## world",
		"# hello\n## world",

	}

	expectedResult := "\n<h1>hello</h1>\n\n<h2>world</h2>\n"
	for i, v := range examples {
		r := blackfriday.Run([]byte(v), chromaRenderer)
		if string(r) != expectedResult {
			t.Errorf("[%d] '%s' != %s", i, string(r), expectedResult)
		} else {
			fmt.Printf("[%d] All good\n", i)
		}
	}
}
```

The first iteration results in text that does NOT contain a trailing new-line, but the second (and further) iterations do.

This is undeterministic in the sense that the same input does not always result in the same output. This causes havoc on testing as depending on the order tests run, I get different results.

Finally, I don't think the trailing new-line was supposed to be there anyway. Using just `blackfriday`, it consistently gives the same output, without the trailing new-line.

**Comment by Depado** [comment]
I think I had a similar issue when I was developing this lib. 
I'll investigate a bit more, but a workaround is to recreate the `chromaRenderer` every time.

I'm on it, anyway, thanks for your input :+1:

**Comment by Depado** [comment]
```go
func TestDeterministicBlackfriday(t *testing.T) {
	renderer := bf.NewHTMLRenderer(bf.HTMLRendererParameters{Flags: bf.CommonHTMLFlags})
	examples := []string{
		"# hello\n## world",
		"# hello\n## world",
	}

	expectedResult := "\n<h1>hello</h1>\n\n<h2>world</h2>\n"
	for i, v := range examples {
		r := bf.Run([]byte(v), bf.WithRenderer(renderer))
		if string(r) != expectedResult {
			t.Errorf("[%d] '%s' != %s", i, string(r), expectedResult)
		} else {
			fmt.Printf("[%d] All good\n", i)
		}
	}
}
```

I just tested that, and it looks like this issue is from blackfriday itself. This test fails with the behavior you described. I don't know why but it seems that when you define a renderer and use it multiple times, it keeps some kind of state ?

**Comment by renatoathaydes** [comment]
I tested Blackfriday without setting anything (no renderer) and it doesn't do this.

I worked around by actually removing the first new-line if the input did not have new-line :D but hopefully this will be fixed soon... My bet is that the issue is with Chroma, not this lib... could it be?

**Comment by Depado** [comment]
Actually in your example test there's no code-block. So there's no reason Chroma will ever be run against that input markdown. This extension is just wrapper, and if there's no code-block, it will just fallback to the defined renderer. 
https://github.com/Depado/bfchroma/blob/master/renderer.go#L109

If you don't provide a new renderer, then I guess Blackfriday will create one for you under the hood ? Note that the test I'm showing you is pure Blackfriday and doesn't use my lib at all. And still fails exactly the same way your test with bfchroma does. 

I suspect **it's not a bug, it's a feature™**, so you can feed a renderer multiple input markdown and it will add a newline to separate the inputs ?

**Comment by renatoathaydes** [comment]
The problem is not whether or not a line is added, the problem is that, if you don't set a custom renderer on blackfriday, it doesn't add the new-line, but if you add one, it does, so the behaviour becomes dependent on the renderer being set or not...

But I agree this is probably done for the reason you mentioned, by some renderers, but not the default one??

Anyway, it's out of the control of this library, from what you've discovered, so I am closing this issue. My workaround is robust and I am pretty sure doing that is more performant than creating a new renderer every time (there's a lot of calls to render in my code). I will benchmark to find out.

**Comment by Depado** [comment]
Thanks for the issue anyway :+1:
